### ISSUE TITLE
implication of the hdf5 file column

### ISSUE THREAD

**Issue by liyongzheng1** [gifford-lab/DeepLigand#2]
Hello, I follow the  README file to run the sample data and get hdf5 result, but I can't understand the meaning of the hdf5 file column, could you explain it, Thank you.
[h5.batch1.tar.gz](https://github.com/gifford-lab/DeepLigand/files/3613556/h5.batch1.tar.gz)

**Comment by haoyangz** [comment]
@liyongzheng1  Hi the file doesn't seem right. It should contain a dataset named "pred" but it is missing. Are you sure you didn't have any problem running the preprocessing step and the prediction step? Can you share the first batch of the output from the processing step? (ie $OUTDIR/test.h5.batch1 in README)

**Comment by liyongzheng1** [comment]
It has a dataset named "pred", I seen it in HDFView, and this can be comfirmed by h5py module in python.
![result_in_HDFView](https://user-images.githubusercontent.com/19150391/65508573-1b741880-df03-11e9-9f34-6f48dd77af43.png)

**Comment by haoyangz** [comment]
Ok after a second try I see it now. I now add more descriptions on how to interpret the predictions in README.

**Comment by liyongzheng1** [comment]
Thank you very much.
